server {
    listen 80 default_server;
    # listen [::]:80 default_server;
    server_name _;
    root {{DEFAULT_DIR}};
    index index.html index.htm index.php;

    access_log /home/wwwlogs/default.log main;
    error_log /home/wwwlogs/default.error.log;

    location ~ \.php$ {
        fastcgi_pass unix:/tmp/php-cgi.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
        fastcgi_param PHP_ADMIN_VALUE "open_basedir={{DEFAULT_DIR}}:/tmp/:/proc/";
    }

    location ~ /\. {
        deny all;
    }

    location ^~ /.well-known/acme-challenge/ {
        allow all;
    }
}
